### ISSUE TITLE
Map server isn't working

### ISSUE THREAD

**Issue by shinjjo** [openplanetary/opm#10]
Hi, 

OPM Mars Basemap v0.1 (vector-based) with label is not working anymore. 
https://cartocdn-ashbu.global.ssl.fastly.net/nmanaud/api/v1/map/named/opm-mars-basemap-v0-1/all/{z}/{x}/{y}.png

![image](https://user-images.githubusercontent.com/3928633/44259390-a4eded00-a211-11e8-93ff-65a99e941035.png)

Could you please check.

**Comment by nmanaud** [comment]
CARTO CDN URLs have changes from cartocdn-ashbu.global.ssl.fastly.net to cartocdn-gusc.global.ssl.fastly.net.

Simply update URLs in your code.

**Comment by nmanaud** [comment]
In additional to the change of the CARTO CDN base URL, I also migrated the basemap underlying datasets to an _opmbuilder_ account (instead of nmanaud) and created a new basemap (v0.1.1) identical (in content and style) to v0.1. 

Please now use: *https://cartocdn-gusc.global.ssl.fastly.net/opmbuilder/api/v1/map/named/opm-mars-basemap-v0-1/all/{z}/{x}/{y}.png*.

(see updated [documentation](https://github.com/openplanetary/opm/wiki/OPM-Mars-Basemap-v0.1))
