### ISSUE TITLE
Basemap error when loading in QGIS

### ISSUE THREAD

**Issue by shinjjo** [openplanetary/opm#6]
Hello, I am Jaeho, drawing polygon Mars map. 
As the screenshot shows, an error occurs when I load the basemap.
(Same problem happens except for OPM Mars Basemap v0.1 ) 

Could you please help.

![screenshot from 2018-03-08 14-37-06](https://user-images.githubusercontent.com/3928633/37153812-33342006-22de-11e8-9266-92faa8f97ecd.png)

**Comment by nmanaud** [comment]
Hi Jaeho,

Thanks for raising this issue.

This is due to the fact that Y axes are inverted for all OPM raster basemaps (generated using gdal2tiles.py). Web clients like Leaflet use a TMS=true parameter to invert Y axis numbering.Using QQIS, you can overcome this by specifying {-y} instead of {y}. 

Try: http://s3-eu-west-1.amazonaws.com/whereonmars.cartodb.net/mola-color/{z}/{x}/{-y}.png
